// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkvvuahwqwfugmaruweq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrdnZ1YWh3cXdmdWdtYXJ1d2VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNTIzNjQsImV4cCI6MjA3NTYyODM2NH0.GB_xY6MHVF0NOMtQEI9NSTnvMbh0ttKLsfo-ZAAAv-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});